### ISSUE TITLE
unable to open camera, camera not connected

### ISSUE THREAD

**Issue by jeremy-rutman** [ncsuarc/ids#14]
I get this error
```
>>> cam=ids.Camera()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ids.py", line 54, in __init__
    super(Camera, self).__init__(*args, **kwargs)
IOError: Unable to open camera. Camera not connected.
```
 even though the ueye demo finds and uses the camera fine - I see video output. 
This happens whether the daemon is running or not .  Any advice appreciated, thanks

**Comment by jeremy-rutman** [comment]
ok so stopping and starting the daemon then setting cam id seems to have worked:

```
sudo /etc/init.d/ueyeusbdrc stop
sudo /etc/init.d/ueyeusbdrc start
ueyesetid
```

**Comment by jasonsychau** [comment]
Hi, were you using a Raspberry Pi? I am able to start daemon, but no camera is detected. With ueyesetid, I get No cameras connected ! under an instruction layout.

Alright, I've found my solution by enable Camera interface from Preferences->Raspberry Pi Configurations->Interfaces.
