### ISSUE TITLE
Installation error for numpy

### ISSUE THREAD

**Issue by ghost** [ncsuarc/ids#16]
I get the below error during installation procedure though numpy is installed and works fine:

running install
running buildrunning build_py
running build_ext
building 'ids_core' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python2.7 -c ids_core/ids_core.c -o build/temp.linux-x86_64-2.7/ids_core/ids_core.o -std=gnu99 -g3
ids_core/ids_core.c:34:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include <numpy/arrayobject.h>
                               ^
compilation terminated.

**Comment by Perseus101** [comment]
Did you install numpy through pip or apt? You need to install it through
apt for the headers to be installed properly.

**Comment by ghost** [comment]
Thank you! it worked perfectly.
