### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by MikeDP** [ncsuarc/ids#17]
Hi,
I'm having an issue during installation (on Linux Mint 18.1).  I have the ids driver, numpy etc. installed and working but the build fails while building the ids_core libraries with the message:
```
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Googleing suggest this is normally a missing library but lz is definitely present (at /usr/bin/lz).
Any suggestions?

**Comment by jasonsychau** [comment]
Have you installed...
   sudo apt-get update
   sudo apt-get install zlib1g-dev
?

**Comment by MikeDP** [comment]
Moved away from IDS camera after unfixed by early 2018.
